#!/usr/bin/env bash
##Created by Edward "edge226" Tunnah.

## The script converts github markdown and produces html from it.

unset md

## Load config and usage file for the framework.
conf=$( find . -name ghmd-ccs.config -type f -print )
usage=$( find . -name ghmd-ccs.usage -type f -print )
source "$conf"
source "$usage"

OPTIND=1 ## make sure the optargs are reset for getopts

while getopts "d:h" opt; do
    case "$opt" in
        d)    md=$OPTARG;; ## The markdown file.
        h)      printf '%s\n' "$ghmd2html_usage"; exit 0;;
        \?)     printf '%s\n' "$ghmd2html_usage" >&2; exit 1;;
    esac
done

write_mu(){ ## Safely writes the .mu (markup) version of the markdown.
    if [[ -f "$md" ]]
    then
    github-markup "$md" ## print out the html for the markdown file.
  fi
}

write_mu
exit 0
