#!/usr/bin/env bash
##Created by Edward "edge226" Tunnah.

## The script converts github markdown into html that can be pasted into the index-template.html to be able
## to easily update and modify the website or potentially multiple websites.
## It convers README.md to a README.mu
## It requires the github-markup command and github-markdown.

## Load config and usage file for the framework.

conf=$( find . -name ghmd-cms.config -type f -print )
usage=$( find . -name ghmd-cms.usage -type f -print )

source "$conf"
source "$usage"

OPTIND=1 ## make sure the optargs are reset for getopts

while getopts "l:m:d:n:h" opt; do
    case "$opt" in
        n)    page=$OPTARG;;
        m)   mu=$OPTARG;;
        d)    md=$OPTARG;;
        l)     loc=$OPTARG;;
        h)      printf '%s\n' "$ghmd2html_usage"; exit 0;;
        \?)     printf '%s\n' "$ghmd2html_usage" >&2; exit 1;;
    esac
done

if [[ -d "$loc" ]]
  then
  cd "$loc" | exit 1
fi

write_mu(){ ## Safely writes the .mu (markup) version of the markdown.
  if [[ -f ./"$md" ]]
    then
    if [[ "$mu" = "README.mu" ]]
      then
      github-markup ./"$md"
    else
      github-markup ./"$md"
    fi
  fi
}

main(){
if [[ "$page" != "" ]]
  ## Checks to see if the page name has been set, finds the directory, enters it then writes the markup file.
  then
  local loc=$( find  ../ -name "$page" -type d -print0 )
  if [[ -d "$loc"  ]]
    ## make sure the directory exists before cd into the directory then write the markup.
    then
    cd "$loc" | exit
    write_mu
  fi
else
  ## Goto the mu file in the current directory.
  write_mu
fi
exit 0
}

main
