#!/usr/bin/env bash
##Created by Edward "edge226" Tunnah.

## The script converts github markdown into html that can be pasted into the index-template.html to be able
## to easily update and modify the website or potentially multiple websites.
## It convers README.md to a README.mu
## It requires the github-markup command.

## Load config and usage file for the framework.
source ./config/ghmd-cms.config
source ./config/ghmd-cms.usage

OPTIND=1 ## make sure the optargs are reset for getopts

while getopts "s:t:n:h" opt; do
    case "$opt" in
        s )   md=$OPTARG;;
        t )   mu=$OPTARG;;
        n)    page=$OPTARG;;
        h)      printf '%s\n' "$checklinks_usage"; exit 0;;
        \?)     printf '%s\n' "$checklinks_usage" >&2; exit 1;;
    esac
done

write_mu(){ ## Safely writes the .mu (markup) version of the markdown.
  if [[ -f ./"$md" ]]
    then
    github-markup ./"$md" > "$mu"
  fi
}

main(){
if [[ "$page" != "" ]]
  ## Checks to see if the page name has been set, finds the directory, enters it then writes the markup file.
  then
  local loc=$( find  ../ -name "$page" -type d -print0 )
  if [[ -d "$loc"  ]]
    ## make sure the directory exists before cd into the directory then write the markup.
    then
    cd "$loc" | exit
    write_mu
  fi
else
  ## Goto the index directory and write the index markup file.
  cd ../ | exit
  write_mu
fi
}

main
