#!/usr/bin/env bash
##Created by Edward "edge226" Tunnah.

## This command will index the website for all README.md files that exist saving to a README.index file
## in the root of the website.

conf=$( find . -name ghmd-cms.config -type f -print )
usage=$( find . -name ghmd-cms.usage -type f -print )

source "$conf"
source "$usage"

while getopts "n:h" opt; do
    case "$opt" in
        n)    md=$OPTARG;;
        h)      printf '%s\n' "$index_usage"; exit 0;;
        \?)     printf '%s\n' "$index_usage" >&2; exit 1;;
    esac
done

main(){
    find . -name "$md" -type f -print > "$index_file"
}
main
