#!/usr/bin/env bash
##Created by Edward "edge226" Tunnah.

## psb pushes the sidebar from a main website to sub websites. It is capable of pushing any template html.
## The only template file that needs to be upgraded on a consistant basis is the sidebar.

source ./config/psb.conf

update_pages(){
  if [[ ! -d ./ghmd-ccs ]]
    then
    chmod a+x ./ghmd-ccs/update
    ./update
  fi
  if [[ -d ./ghmd-ccs ]]
  then
    chmod a+x ./ghmd-ccs/update
    ./ghmd-ccs/update
  fi
}

for subdir in "${sub_sites[@]}"
do
  printf '\n%s %s%s%s\n' "Updating " "$site_dir" "/" "$subdir"
  cd "$site_dir/$subdir" || exit
  branch=$(git symbolic-ref --short HEAD)
  git checkout gh-pages
  for file in "${update_files[@]}"
  do
    rsync -rvp "$site_dir/$main_site/template/$file" "$site_dir/$subdir/template/"
  done
  update_pages
  git commit -a -m "Updated sidebar menu content."
  git push origin gh-pages
  git checkout "$branch"
done
