#!/usr/bin/env bash
##Created by Edward "edge226" Tunnah.

## This command will index the website for all README.md files that exist saving to a variable and output to a new index.html.

conf=$( find . -name ghmd-ccs.config -type f -print )
usage=$( find . -name ghmd-ccs.usage -type f -print )
g2h=$( find . -name ghmd2html -type f -print )


source "$conf"
source "$usage"

while getopts "d:m:h" opt; do
    case "$opt" in
        m) mu=$OPTARG;;
        d)    md=$OPTARG;;
        h)      printf '%s\n' "$update_usage"; exit 0;;
        \?)     printf '%s\n' "$update_usage" >&2; exit 1;;
    esac
done

get_mds(){
  index_md=( $( find . -name "$md" -type f -print ) )
}

get_loc(){
  unset loc
  local struct="$1"
  loc=${struct%/*.md}
  loc="$loc/"
}

get_name(){
  printf '\n%s %s\n' "location is currently" "$loc"
  if [[ "$loc" != "" ]] && [[ "$loc" != "./" ]]
    then
    name=${loc%"/"}
    name=${name##*/}
    printf '\n%s %s\n' "name is:" "$name"
  fi
}

get_template(){
  get_name
  if [[ -f  "$loc""template/index-template.html" ]]
    then
    printf '\n%s %s%s\n' "Setting template to:" "$loc" "template/index-template.html"
    template="$loc""template/index-template.html"
    downloads="$loc""template/downloads.html"
    sidebar="$loc""template/sidebar.html"
    loadcss="$loc""template/css.html"

  else
    printf '\n%s %s\n' "loc is" "$loc"
    pwd
    local temp_loc=${loc%/*/}
    printf '\n%s %s\n' "temp_loc is" "$temp_loc"
    template="$temp_loc""/template/index-template.html"
    printf '\n%s %s\n' "temp_loc is" "$temp_loc"
    downloads="$temp_loc""/template/downloads.html"
    printf '\n%s %s\n' "temp_loc is" "$temp_loc"
    sidebar="$temp_loc""/template/sidebar.html"
    loadcss="$temp_loc""/template/css.html"
    printf '\n%s %s\n' "template has been set to:" "$template"
    printf '\n%s %s\n' "downloads has been set to:" "$downloads"
    printf '\n%s %s\n' "sidebar has been set to:" "$sidebar"
    printf '\n%s %s\n' "loadcss has been set to:" "$loadcss"
  fi
}

main(){
    get_mds
    for page in "${index_md[@]}"
    do
      get_loc "$page"

      get_template

      printf '\n\n%s %s\n' "The location of the current output file is:" "$loc$mu"
      printf '%s %s\n' "The current page is: " "$page"

        mu=${page##*/}
        if [[ "$mu" = "README.md" ]]
          then
          mu="index.html"
        else
          mu=${mu%%.md}
          mu="$mu.html"
        fi
        printf '\n%s %s\n' "mu is set to:" "$mu"

      if [[ -f "$loc$mu" ]]
        then
        rm "$loc$mu"
      fi

      if [[ ! -f "$loc$mu" ]]
        then
        touch "$loc$mu"
        printf '\n%s %s\n' "Now we are writing to:" "$loc$mu"
      fi
        printf '\n%s %s\n' "The template file is:" "$template"

      while IFS= read -r line; do ## Read through the file.
        if [[ "$line" = *"<p>Downloads.</p>"* ]]
          then
          ## printf '\n%s %s\n' "This is what downloads is set to:" "$downloads"
          ##cat "$downloads"
          cat "$downloads" >> "$loc$mu"
        elif [[ "$line" = *"<p>Sidebar.</p>"* ]]
          then
          printf '\n%s %s\n' "This is what sidebar is set to:" "$sidebar"
          ##cat "$sidebar"
          cat "$sidebar" >> "$loc$mu"
        elif [[ "$line" = *"  <p>Load CSS.</p>"* ]]
            then
            printf '\n%s %s\n' "This is what loadcss is set to:" "$loadcss"
            ##cat "$loadcss"
            cat "$loadcss" >> "$loc$mu"
        elif [[ "$line" = *"<p>Template.</p>"* ]]
          then
          #printf '\n%s %s %s %s %s %s\n' "Running the " "$g2h" "Command and it should write this output to" "$loc$mu" "using data from" "$page"
          #"$g2h" -d "$page" ## >> "$loc$mu"
          "$g2h" -d "$page" >> "$loc$mu"
        else
          #printf '%s\n' "$line"
          printf '%s\n' "$line" >> "$loc$mu"
        fi
      done < "$template" ## The template file is what is read.
    done
    exit 0
}
main
