#!/usr/bin/env bash
##Created by Edward "edge226" Tunnah.

## loc=""

for md in "$loc"*.md
do
  if [[ "$md" != "README.md" ]]
    then
    md=${md##*/}
    mu=${md%%.md}
    mu="$mu.html"
    printf '\n%s %s %s %s\n' "Updating" "$mu" "from" "$md"
    update -m "$mu" -d "$md"
  fi
done
